### ISSUE TITLE
采样方式的疑惑

### ISSUE THREAD

**Issue by elevenjiang1** [zhaoxuhui/ROS-Bag-Tools#2]
您好, 有些好奇为什么您的改变topic帧率的方式是没有索引header里面的时间进行解析?(主要是参考changeBagFramerate.py)
我目前有一个需求是有多个topic的信息想去做多信息融合,为此希望能用同一个频率对多个topic进行采样;一个非常直接的方式就是索引时间戳找最近的数据,不知道您的代码中是否有这个功能实现呢?

谢谢~

**Comment by zhaoxuhui** [comment]
你好，根据你的描述，目前没有这样的功能。如果需要的话之后有时间会更新一些脚本，实现你提到的这些功能。至于你说到的header我之前没太了解过。有空会看看，谢谢！

**Comment by elevenjiang1** [comment]
感谢您的回复,即使没有对应的功能,参考您的代码也让我很方便地实现了我想要的功能~
我说的header指的是每个消息里面的时间戳 stamp; 
```
header: 
  seq: 6294431
  stamp: 
    secs: 1642591010
    nsecs: 215862198
```
其实本身想问的是为什么使用changeBagFramerate.py的方式进行rosbag中的帧率改变,这种方法的好处是什么呢? 比如我有一个Camera和一个IMU,希望去做Fusion,即采集同一时刻/相近时刻的RGBD和IMU数据,然后进行处理.我就直接索引了他们的time stamp然后找最近的去融合,不知道您这里面方式的好处是?或者也许changeBagFramerate.py本身并不是为了做Fusion而写的?

感谢~
